### ISSUE TITLE
Sidekiq実行中にDocker::Error::TimeoutErrorが発生する

### ISSUE THREAD

**Issue by hanasuke** [hanasuke/wing-cs-front#34]
Sidekiqによる対戦処理の実行中、Docker::Error::TimeoutErrorが発生する。
いまのところ原因が不明。

**Comment by hanasuke** [comment]
当該ログ
```
2017-02-06T12:58:34.002Z 12781 TID-ou7q2vvng FirstBattleWorker JID-370fe7e4f697356bc7b075e2 INFO: start
2017-02-06T12:59:41.042Z 12781 TID-ou7q2vvng FirstBattleWorker JID-370fe7e4f697356bc7b075e2 INFO: fail: 67.04 sec
2017-02-06T12:59:41.042Z 12781 TID-ou7q2vvng WARN: {"context":"Job raised exception","job":{"class":"FirstBattleWorker","args":[201],"retry":10,"queue":"default","dead":false,"jid":"370fe7e4f697356bc7b075e2","created_at":1486385914.0016518,"enqueued_at":1486385914.0017045,"error_message":"read timeout reached","error_class":"Docker::Error::TimeoutError","failed_at":1486385981.0418026,"retry_count":0},"jobstr":"{\"class\":\"FirstBattleWorker\",\"args\":[201],\"retry\":10,\"queue\":\"default\",\"dead\":false,\"jid\":\"370fe7e4f697356bc7b075e2\",\"created_at\":1486385914.0016518,\"enqueued_at\":1486385914.0017045}"}
2017-02-06T12:59:41.042Z 12781 TID-ou7q2vvng WARN: Docker::Error::TimeoutError: read timeout reached
2017-02-06T12:59:41.042Z 12781 TID-ou7q2vvng WARN: /home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/docker-api-1.33.1/lib/docker/connection.rb:52:in `rescue in request'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/docker-api-1.33.1/lib/docker/connection.rb:38:in `request'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/docker-api-1.33.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/docker-api-1.33.1/lib/docker/exec.rb:73:in `start!'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/docker-api-1.33.1/lib/docker/container.rb:91:in `exec'
/home/app/GameExrc/wing-cs-front/lib/strategy_manager/first_battle_manager.rb:34:in `create_execution_container'
/home/app/GameExrc/wing-cs-front/lib/strategy_manager.rb:15:in `exec_first_battle'
/home/app/GameExrc/wing-cs-front/app/workers/first_battle_worker.rb:17:in `perform'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by hanasuke** [comment]
これが起こった後、戦略登録が再度発生(ref #35)し、その後何故か対戦が実行されない…

**Comment by hanasuke** [comment]
このあたり原因くさい
https://github.com/swipely/docker-api/issues/106
