### ISSUE TITLE
Sidekiqのジョブ生成時に ActiveRecord::ConnectionTimeoutError

### ISSUE THREAD

**Issue by hanasuke** [hanasuke/wing-cs-front#42]
## 概要

提出受付後の非同期処理へ移行したとき、 `ActiveRecord::ConnectionTimeoutError` が発生することがある。

## 原因

一切不明ではあるが、発生したと考えられるとき、LoadAverageが20程度になっていた。

## 当該ログ

```
2017-02-18T12:11:01.082Z 29436 TID-osv730yo4 FirstBattleWorker JID-bd729dcd5ba57b9608c5e495 INFO: start
2017-02-18T12:11:06.083Z 29436 TID-osv730yo4 FirstBattleWorker JID-bd729dcd5ba57b9608c5e495 INFO: fail: 5.0 sec
2017-02-18T12:11:06.083Z 29436 TID-osv730yo4 WARN: {"context":"Job raised exception","job":{"class":"FirstBattleWorker","args":[365],"retry":10,"queue":"default","dead":false,"jid":"bd729dcd5ba57b9608c5e495","created_at":1487403598.4979596,"enqueued_at":1487419861.0820959,"error_message":"could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)","error_class":"ActiveRecord::ConnectionTimeoutError","failed_at":1487403603.5001247,"retry_count":10,"retried_at":1487419866.0829825},"jobstr":"{\"class\":\"FirstBattleWorker\",\"args\":[365],\"retry\":10,\"queue\":\"default\",\"dead\":false,\"jid\":\"bd729dcd5ba57b9608c5e495\",\"created_at\":1487403598.4979596,\"enqueued_at\":1487419861.0820959,\"error_message\":\"could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)\",\"error_class\":\"ActiveRecord::ConnectionTimeoutError\",\"failed_at\":1487403603.5001247,\"retry_count\":9,\"retried_at\":1487413154.0949407}"}
2017-02-18T12:11:06.083Z 29436 TID-osv730yo4 WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2017-02-18T12:11:06.083Z 29436 TID-osv730yo4 WARN: /home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
/home/usr/assist/_naosuke/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/usr/assist/_naosuke/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/usr/assist/_naosuke/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:153:in `find'
/home/app/GameExrc/wing-cs-front/app/workers/first_battle_worker.rb:8:in `perform'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/home/app/GameExrc/wing-cs-front/.bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by hanasuke** [comment]
<img width="994" alt="screen shot 2017-02-18 at 22 39 58" src="https://cloud.githubusercontent.com/assets/2376843/23093604/5946dcb0-f62b-11e6-9830-bdb07b8432c4.png">

**Comment by hanasuke** [comment]
負荷が高まると起こっている印象

**Comment by hanasuke** [comment]
Sidekiqのジョブ上でコネクションが張られ続けており、connection_poolが枯渇したのが原因でした。
現在本番環境ではhotfixとして、明示的にActiveRecordのコネクションを切っています。
また、DBのpool数もふやしました。

念のため、Sidekiqのプロセス数も減らしておこうと思います。

**Comment by hanasuke** [comment]
修正済みなのでクローズ!
